import { JSX } from "react";
import { BasicChannelTabsProps, ChannelTabsProps } from "./types";
export declare const openedTabs: ChannelTabsProps[];
export declare function createTab(props: BasicChannelTabsProps | ChannelTabsProps, switchToTab?: boolean, messageId?: string, save?: boolean): void;
export declare function closeTab(id: number): void;
export declare function closeOtherTabs(id: number): void;
export declare function closeTabsToTheRight(id: number): void;
export declare function closeTabsToTheLeft(id: number): void;
export declare function handleChannelSwitch(ch: BasicChannelTabsProps): void;
export declare function hasClosedTabs(): boolean;
export declare function isTabSelected(id: number): boolean;
export declare function moveDraggedTabs(index1: number, index2: number): void;
export declare function moveToTab(id: number): void;
export declare function openStartupTabs(props: BasicChannelTabsProps & {
    userId: string;
}, setUserId: (id: string) => void): void;
export declare function reopenClosedTab(): void;
export declare const saveTabs: (userId: string) => Promise<void>;
export declare function setOpenTab(id: number): void;
export declare function setUpdaterFunction(fn: () => void): void;
export declare function switchChannel(ch: BasicChannelTabsProps): void;
export declare function toggleCompactTab(id: number): void;
export declare function useGhostTabs(): JSX.Element[];
