blank_issues_enabled: false
contact_links:
    - name: Plexcord Support Server
      url: https://discord.gg/5backnRhY9
      about: If you need help regarding Plexcord, please join our support server!
    - name: Plexcord Installer
      url: https://github.com/Plexcord/Installer
      about: You can find the Plexcord Installer here
