import { IpcMainInvokeEvent } from "electron";
import { getSettings } from "./settings";
export * from "./updater";
import { LoggedAttachment } from "../types";
export { getSettings };
export declare function messageLoggerEnhancedUniqueIdThingyIdkMan(): void;
export declare const getNativeSavedImages: () => Map<string, string>;
export declare function initDirs(): Promise<void>;
export declare function init(_event: IpcMainInvokeEvent): Promise<void>;
export declare function getImageNative(_event: IpcMainInvokeEvent, attachmentId: string): Promise<Uint8Array | Buffer | null>;
export declare function writeImageNative(_event: IpcMainInvokeEvent, filename: string, content: Uint8Array): Promise<void>;
export declare function deleteFileNative(_event: IpcMainInvokeEvent, attachmentId: string): Promise<void>;
export declare function writeLogs(_event: IpcMainInvokeEvent, contents: string): Promise<void>;
export declare function getDefaultNativeImageDir(): Promise<string>;
export declare function getDefaultNativeDataDir(): Promise<string>;
export declare function chooseDir(event: IpcMainInvokeEvent, logKey: "logsDir" | "imageCacheDir"): Promise<string>;
export declare function showItemInFolder(_event: IpcMainInvokeEvent, filePath: string): Promise<void>;
export declare function chooseFile(_event: IpcMainInvokeEvent, title: string, filters: Electron.FileFilter[], defaultPath?: string): Promise<string>;
export declare function downloadAttachment(_event: IpcMainInvokeEvent, attachemnt: LoggedAttachment, attempts?: number, useOldUrl?: boolean): Promise<{
    error: string | null;
    path: string | null;
}>;
