type PolicyMap = Record<string, string[]>;
export declare const ConnectSrc: string[];
export declare const ImageSrc: string[];
export declare const CssSrc: string[];
export declare const ImageAndCssSrc: string[];
export declare const ImageScriptsAndCssSrc: string[];
export declare const CSPSrc: string[];
export declare const CspPolicies: PolicyMap;
export declare function initCsp(): void;
export {};
